### ISSUE TITLE
Création du job rebelle

### ISSUE THREAD

**Issue by MathieuCooper** [milou2764/militaryrp#5]
[](url)Armement : 

cw_kk_ins2_makarov
cw_kk_ins2_nade_molotov
cw_kk_ins2_mosin
cw_kk_ins2_rpg
cw_kk_ins2_nade_ied
cw_kk_ins2_ak74
cw_kk_ins2_nade_m18
cw_kk_ins2_rpk

Skin : [https://steamcommunity.com/sharedfiles/filedetails/?id=2313817086](url)

**Comment by milou2764** [comment]
Est-ce qu'on peut fermer cette issue ?
