### ISSUE TITLE
Problème en maintenant la touche ALT

### ISSUE THREAD

**Issue by MathieuCooper** [milou2764/militaryrp#6]
Normalement utilisée pour marcher, la touche vérouille aussi la vision (comme dans les tourelles véhicules) ce qui provoque un glitch et permet de voir de façon déformée le player model. 

Solution proposée : mettre la marche par défaut.

**Comment by milou2764** [comment]
Le bug vient de cet [https://steamcommunity.com/sharedfiles/filedetails/?id=2816296516](addon).
Pour corriger le bug on va retirer le bind par défaut de la commande +freelook et laisser les joueurs attribuer eux-mêmes une touche à cette commande s'ils veulent profiter de la fonctionnalité.

**Comment by milou2764** [comment]
Merci d'avoir trouvé le bug
