### ISSUE TITLE
Spam possible du loot des caisses

### ISSUE THREAD

**Issue by MathieuCooper** [milou2764/militaryrp#7]
Les caisses de ravitaillement peux nous mettre à mal avec le spam, les entités ne disparaissent pas et cela peut être un problème d'optimisation futur

**Comment by milou2764** [comment]
Actuellement, utiliser la caisse alors qu'une entité est posée dessus ne fera rien
C'est notre protection contre les spams
Si tu penses que ce n'est pas assez, on peut directement équiper l'entité dans l'inventaire du joueur au lieu de faire apparaître l'entité.
Tu préfères rester dans l'état actuel ou implémenter la solution que je viens de te proposer >

**Comment by MathieuCooper** [comment]
Ca peux être une solution, mais par exemple, si on veux changer de gilet on dois poser le notre par terre et en prendre un nouveau, faisant ainsi une entité non-utile

**Comment by milou2764** [comment]
Je te propose que les entités se suppriment toute seules après 30 sec

**Comment by milou2764** [comment]
dit moi si ça te convient puis j'implémente

**Comment by MathieuCooper** [comment]
ça me va, mais ça ne risque pas de delete aussi les caisses ?

**Comment by milou2764** [comment]
non

**Comment by MathieuCooper** [comment]
Et bah go
